# Generated by Django 5.2.5 on 2025-08-27 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Order Created'), ('new_order', 'New Order'), ('order_updated', 'Order Updated'), ('order_canceled', 'Order Canceled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('system', 'System'), ('info', 'Information'), ('warning', 'Warning'), ('error', 'Error')], help_text='Type of notification', max_length=50, verbose_name='type')),
                ('title', models.CharField(help_text='Notification title', max_length=255, verbose_name='title')),
                ('message', models.TextField(help_text='Notification message content', verbose_name='message')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', help_text='Current status of the notification', max_length=20, verbose_name='status')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=1, help_text='Notification priority level', verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created', verbose_name='created at')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True, verbose_name='read at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data', verbose_name='metadata')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who should receive the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent the notification (null for system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'websocket_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='websocket_n_recipie_d1d267_idx'), models.Index(fields=['type'], name='websocket_n_type_945381_idx'), models.Index(fields=['created_at'], name='websocket_n_created_54916b_idx'), models.Index(fields=['priority'], name='websocket_n_priorit_feb575_idx')],
            },
        ),
    ]
